-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 19:00:22 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dwe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dwe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwe` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dwe` ;

-- -----------------------------------------------------
-- Table `dwe`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`User` (
  `US_idUser` INT NOT NULL AUTO_INCREMENT,
  `US_nom` TEXT NULL,
  `US_prenom` VARCHAR(45) NULL,
  `US_pays` TEXT NULL,
  `US_ville` TEXT NULL,
  `US_adresse` VARCHAR(45) NULL,
  `US_codepostale` INT NULL,
  `US_pseudo` VARCHAR(45) NULL,
  `US_mail` VARCHAR(45) NULL,
  `US_mdp` VARCHAR(45) NULL,
  `US_datenaissance` VARCHAR(45) NULL,
  `US_admin` VARCHAR(45) NULL,
  `US_moderateur` TINYINT(1) NULL,
  `US_like` INT NULL,
  PRIMARY KEY (`US_idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`Produit` (
  `PR_idP` INT NOT NULL AUTO_INCREMENT,
  `PR_nom` TEXT NULL,
  `PR_unite` TINYINT(1) NULL,
  PRIMARY KEY (`PR_idP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`PropositionEchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`PropositionEchange` (
  `PE_idPropositionEchan` INT NOT NULL AUTO_INCREMENT,
  `PR_idP` INT NOT NULL,
  `PE_photos` VARCHAR(45) NULL,
  `PE_quantite` VARCHAR(45) NULL,
  PRIMARY KEY (`PE_idPropositionEchan`),
  INDEX `fk_PropositionEchange_Produit1_idx` (`PR_idP` ASC),
  CONSTRAINT `fk_PropositionEchange_Produit1`
    FOREIGN KEY (`PR_idP`)
    REFERENCES `dwe`.`Produit` (`PR_idP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`Annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`Annonce` (
  `AN_idAnnonce` INT NOT NULL AUTO_INCREMENT,
  `US_idUserannonceur` INT NOT NULL,
  `PR_idP` INT NOT NULL,
  `PE_idPropositionEchan` INT NOT NULL,
  `AN_quantite` INT NULL,
  `AN_prix` INT NULL,
  `AN_echangeok` TINYINT(1) NULL,
  `AN_echangedescription` TEXT NULL,
  `AN_moyentpayment` VARCHAR(45) NULL,
  `AN_moyenenvoie` TINYINT(1) NULL,
  `AN_datepublication` DATE NULL,
  `AN_prixcolis` INT NULL,
  PRIMARY KEY (`AN_idAnnonce`),
  INDEX `fk_Annonce_User_idx` (`US_idUserannonceur` ASC),
  INDEX `fk_Annonce_Produit1_idx` (`PR_idP` ASC),
  INDEX `fk_Annonce_PropositionEchange1_idx` (`PE_idPropositionEchan` ASC),
  CONSTRAINT `fk_Annonce_User`
    FOREIGN KEY (`US_idUserannonceur`)
    REFERENCES `dwe`.`User` (`US_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_Produit1`
    FOREIGN KEY (`PR_idP`)
    REFERENCES `dwe`.`Produit` (`PR_idP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_PropositionEchange1`
    FOREIGN KEY (`PE_idPropositionEchan`)
    REFERENCES `dwe`.`PropositionEchange` (`PE_idPropositionEchan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`Transaction` (
  `TR_idTran` INT NOT NULL AUTO_INCREMENT,
  `US_idUseracheteur` INT NOT NULL,
  `AN_idAnnonce` INT NOT NULL,
  `TR_typeenvoie` TINYINT(1) NULL,
  `TR_typepayment` TINYINT(1) NULL,
  `TR_typetransaction` TINYINT(1) NULL,
  PRIMARY KEY (`TR_idTran`),
  INDEX `fk_Transaction_User1_idx` (`US_idUseracheteur` ASC),
  INDEX `fk_Transaction_Annonce1_idx` (`AN_idAnnonce` ASC),
  CONSTRAINT `fk_Transaction_User1`
    FOREIGN KEY (`US_idUseracheteur`)
    REFERENCES `dwe`.`User` (`US_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Annonce1`
    FOREIGN KEY (`AN_idAnnonce`)
    REFERENCES `dwe`.`Annonce` (`AN_idAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`FAQR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`FAQR` (
  `FR_idFAQR` INT NOT NULL AUTO_INCREMENT,
  `US_idUser` INT NOT NULL,
  `FR_date` DATE NULL,
  `FR_reponse` TEXT NULL,
  PRIMARY KEY (`FR_idFAQR`),
  INDEX `fk_FAQR_User1_idx` (`US_idUser` ASC),
  CONSTRAINT `fk_FAQR_User1`
    FOREIGN KEY (`US_idUser`)
    REFERENCES `dwe`.`User` (`US_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`FAQQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`FAQQ` (
  `FAQQ_idFAQQ` INT NOT NULL AUTO_INCREMENT,
  `US_idUser` INT NOT NULL,
  `FR_idFAQR` INT NOT NULL,
  `FQ_contenu` TEXT NULL,
  `FQ_sujet` VARCHAR(45) NULL,
  `FAQ_date` DATE NULL,
  PRIMARY KEY (`FAQQ_idFAQQ`),
  INDEX `fk_FAQQ_User1_idx` (`US_idUser` ASC),
  INDEX `fk_FAQQ_FAQR1_idx` (`FR_idFAQR` ASC),
  CONSTRAINT `fk_FAQQ_User1`
    FOREIGN KEY (`US_idUser`)
    REFERENCES `dwe`.`User` (`US_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FAQQ_FAQR1`
    FOREIGN KEY (`FR_idFAQR`)
    REFERENCES `dwe`.`FAQR` (`FR_idFAQR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`Commentaire` (
  `CO_idCommentaire` INT NOT NULL AUTO_INCREMENT,
  `US_idUser` INT NOT NULL,
  `CO_like` INT NULL,
  `CO_contenu` TEXT NULL,
  `CO_date` DATE NULL,
  PRIMARY KEY (`CO_idCommentaire`),
  INDEX `fk_Commentaire_User1_idx` (`US_idUser` ASC),
  CONSTRAINT `fk_Commentaire_User1`
    FOREIGN KEY (`US_idUser`)
    REFERENCES `dwe`.`User` (`US_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`Blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`Blog` (
  `BL_idBlog` INT NOT NULL AUTO_INCREMENT,
  `BL_date` DATE NULL,
  `Blogcol` VARCHAR(45) NULL,
  PRIMARY KEY (`BL_idBlog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwe`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwe`.`Article` (
  `AR_idArticle` INT NOT NULL AUTO_INCREMENT,
  `US_idUser` INT NOT NULL,
  `CO_idCommentaire` INT NOT NULL,
  `BL_idBlog` INT NOT NULL,
  `AR_date` DATE NULL,
  `AR_sujet` VARCHAR(45) NULL,
  `AR_contenu` TEXT NULL,
  PRIMARY KEY (`AR_idArticle`),
  INDEX `fk_Article_User1_idx` (`US_idUser` ASC),
  INDEX `fk_Article_Commentaire1_idx` (`CO_idCommentaire` ASC),
  INDEX `fk_Article_Blog1_idx` (`BL_idBlog` ASC),
  CONSTRAINT `fk_Article_User1`
    FOREIGN KEY (`US_idUser`)
    REFERENCES `dwe`.`User` (`US_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_Commentaire1`
    FOREIGN KEY (`CO_idCommentaire`)
    REFERENCES `dwe`.`Commentaire` (`CO_idCommentaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_Blog1`
    FOREIGN KEY (`BL_idBlog`)
    REFERENCES `dwe`.`Blog` (`BL_idBlog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
