-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 10:18:14 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Membres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Membres` (
  `Me_idMembres` INT NOT NULL,
  `Me_Nom` TEXT(50) NULL,
  `Me_Prenom` TEXT(50) NULL,
  `Me_Pays` TEXT(50) NULL,
  `Me_Ville` VARCHAR(45) NULL,
  `Me_Adresse` VARCHAR(45) NULL,
  `Me_Code postale` INT NULL,
  `Me_Mail` VARCHAR(45) NULL,
  `Me_Pseudo` VARCHAR(45) NULL,
  `Me_Mdp` VARCHAR(45) NULL,
  `Me_Datenaissance` DATE NULL,
  `Me_Admin` TINYINT(1) NULL,
  `Me_Modérateur` TINYINT(1) NULL,
  PRIMARY KEY (`Me_idMembres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produits` (
  `Pr_idProduits` INT NOT NULL AUTO_INCREMENT,
  `Pr_Nom` VARCHAR(45) NULL,
  `Pr_Description` TEXT(255) NULL,
  `Pr_Date-péremption` DATE NULL,
  `Pr_Date-récolte` DATE NULL,
  `Pr_Prix` INT NULL,
  `Pr_Quantité` FLOAT NULL,
  PRIMARY KEY (`Pr_idProduits`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAQQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAQQ` (
  `Fq_idFAQ` INT NOT NULL AUTO_INCREMENT,
  `Fq_Sujet` VARCHAR(45) NULL,
  `Fq_Date` DATE NULL,
  `Fq_Contenu` TEXT(255) NULL,
  `Membres_Me_idMembres` INT NOT NULL,
  PRIMARY KEY (`Fq_idFAQ`, `Membres_Me_idMembres`),
  INDEX `fk_FAQQ_Membres1_idx` (`Membres_Me_idMembres` ASC),
  CONSTRAINT `fk_FAQQ_Membres1`
    FOREIGN KEY (`Membres_Me_idMembres`)
    REFERENCES `mydb`.`Membres` (`Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAQR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAQR` (
  `Fr_idFAQ` INT NOT NULL AUTO_INCREMENT,
  `Fr_Réponse` TEXT(255) NULL,
  `Fr_Date` DATE NULL,
  `Membres_Me_idMembres` INT NOT NULL,
  `FAQQ_Fq_idFAQ` INT NOT NULL,
  `FAQQ_Membres_Me_idMembres` INT NOT NULL,
  PRIMARY KEY (`Fr_idFAQ`, `Membres_Me_idMembres`, `FAQQ_Fq_idFAQ`, `FAQQ_Membres_Me_idMembres`),
  INDEX `fk_FAQR_Membres1_idx` (`Membres_Me_idMembres` ASC),
  INDEX `fk_FAQR_FAQQ1_idx` (`FAQQ_Fq_idFAQ` ASC, `FAQQ_Membres_Me_idMembres` ASC),
  CONSTRAINT `fk_FAQR_Membres1`
    FOREIGN KEY (`Membres_Me_idMembres`)
    REFERENCES `mydb`.`Membres` (`Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FAQR_FAQQ1`
    FOREIGN KEY (`FAQQ_Fq_idFAQ` , `FAQQ_Membres_Me_idMembres`)
    REFERENCES `mydb`.`FAQQ` (`Fq_idFAQ` , `Membres_Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blog` (
  `Bl_idBlog` INT NOT NULL AUTO_INCREMENT,
  `Bl_Date` DATE NULL,
  `Bl_Aime` INT NULL,
  `Bl_Membre-aime` INT NULL,
  PRIMARY KEY (`Bl_idBlog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Article` (
  `Ar_idArticle` INT NOT NULL,
  `Ar_Contenu` TEXT(255) NULL,
  `Ar_Date` DATE NULL,
  `Ar_Sujet` VARCHAR(45) NULL,
  `Membres_Me_idMembres` INT NOT NULL,
  `Blog_Bl_idBlog` INT NOT NULL,
  PRIMARY KEY (`Ar_idArticle`, `Membres_Me_idMembres`, `Blog_Bl_idBlog`),
  INDEX `fk_Article_Membres1_idx` (`Membres_Me_idMembres` ASC),
  INDEX `fk_Article_Blog1_idx` (`Blog_Bl_idBlog` ASC),
  CONSTRAINT `fk_Article_Membres1`
    FOREIGN KEY (`Membres_Me_idMembres`)
    REFERENCES `mydb`.`Membres` (`Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_Blog1`
    FOREIGN KEY (`Blog_Bl_idBlog`)
    REFERENCES `mydb`.`Blog` (`Bl_idBlog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commentaire` (
  `Cm_idCommentaire` INT NOT NULL AUTO_INCREMENT,
  `Cm_Date` VARCHAR(45) NULL,
  `Cm_Contenu` TEXT(255) NULL,
  `Cm_Aime` INT NULL,
  `Membres_Me_idMembres` INT NOT NULL,
  `Article_Ar_idArticle` INT NOT NULL,
  `Article_Membres_Me_idMembres` INT NOT NULL,
  PRIMARY KEY (`Cm_idCommentaire`, `Membres_Me_idMembres`, `Article_Ar_idArticle`, `Article_Membres_Me_idMembres`),
  INDEX `fk_Commentaire_Membres1_idx` (`Membres_Me_idMembres` ASC),
  INDEX `fk_Commentaire_Article1_idx` (`Article_Ar_idArticle` ASC, `Article_Membres_Me_idMembres` ASC),
  CONSTRAINT `fk_Commentaire_Membres1`
    FOREIGN KEY (`Membres_Me_idMembres`)
    REFERENCES `mydb`.`Membres` (`Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Article1`
    FOREIGN KEY (`Article_Ar_idArticle` , `Article_Membres_Me_idMembres`)
    REFERENCES `mydb`.`Article` (`Ar_idArticle` , `Membres_Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits_has_Membres1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produits_has_Membres1` (
  `Produits_Pr_idProduits` INT NOT NULL,
  `Membres_Me_idMembres` INT NOT NULL,
  PRIMARY KEY (`Produits_Pr_idProduits`, `Membres_Me_idMembres`),
  INDEX `fk_Produits_has_Membres1_Membres1_idx` (`Membres_Me_idMembres` ASC),
  INDEX `fk_Produits_has_Membres1_Produits1_idx` (`Produits_Pr_idProduits` ASC),
  CONSTRAINT `fk_Produits_has_Membres1_Produits1`
    FOREIGN KEY (`Produits_Pr_idProduits`)
    REFERENCES `mydb`.`Produits` (`Pr_idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits_has_Membres1_Membres1`
    FOREIGN KEY (`Membres_Me_idMembres`)
    REFERENCES `mydb`.`Membres` (`Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Annonce` (
  `An_idAnnonce` INT NOT NULL AUTO_INCREMENT,
  `An_Publication` DATE NULL,
  `An_Type-vente` TINYINT(1) NULL,
  `Produits_has_Membres1_Produits_Pr_idProduits` INT NOT NULL,
  `Produits_has_Membres1_Membres_Me_idMembres` INT NOT NULL,
  PRIMARY KEY (`An_idAnnonce`),
  INDEX `fk_Annonce_Produits_has_Membres11_idx` (`Produits_has_Membres1_Produits_Pr_idProduits` ASC, `Produits_has_Membres1_Membres_Me_idMembres` ASC),
  CONSTRAINT `fk_Annonce_Produits_has_Membres11`
    FOREIGN KEY (`Produits_has_Membres1_Produits_Pr_idProduits` , `Produits_has_Membres1_Membres_Me_idMembres`)
    REFERENCES `mydb`.`Produits_has_Membres1` (`Produits_Pr_idProduits` , `Membres_Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits_has_Membres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produits_has_Membres` (
  `Produits_idProduits` INT NOT NULL,
  `Membres_idMembres` INT NOT NULL,
  `Membres_Produits_idProduits` INT NOT NULL,
  `Membres_FAQ (questions)_idFAQ (questions)` INT NOT NULL,
  `Membres_FAQ (Réponse)_idFAQ (Réponse)` INT NOT NULL,
  `Membres_Article_idArticle` INT NOT NULL,
  PRIMARY KEY (`Produits_idProduits`, `Membres_idMembres`, `Membres_Produits_idProduits`, `Membres_FAQ (questions)_idFAQ (questions)`, `Membres_FAQ (Réponse)_idFAQ (Réponse)`, `Membres_Article_idArticle`),
  INDEX `fk_Produits_has_Membres_Membres1_idx` (`Membres_idMembres` ASC, `Membres_Produits_idProduits` ASC, `Membres_FAQ (questions)_idFAQ (questions)` ASC, `Membres_FAQ (Réponse)_idFAQ (Réponse)` ASC, `Membres_Article_idArticle` ASC),
  INDEX `fk_Produits_has_Membres_Produits1_idx` (`Produits_idProduits` ASC),
  CONSTRAINT `fk_Produits_has_Membres_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`Pr_idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits_has_Membres_Membres1`
    FOREIGN KEY (`Membres_idMembres`)
    REFERENCES `mydb`.`Membres` (`Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Membres_has_Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Membres_has_Produits` (
  `Membres_idMembres` INT NOT NULL,
  `Membres_Produits_idProduits` INT NOT NULL,
  `Membres_FAQ (questions)_idFAQ (questions)` INT NOT NULL,
  `Membres_FAQ (Réponse)_idFAQ (Réponse)` INT NOT NULL,
  `Membres_Article_idArticle` INT NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  PRIMARY KEY (`Membres_idMembres`, `Membres_Produits_idProduits`, `Membres_FAQ (questions)_idFAQ (questions)`, `Membres_FAQ (Réponse)_idFAQ (Réponse)`, `Membres_Article_idArticle`, `Produits_idProduits`),
  INDEX `fk_Membres_has_Produits_Produits1_idx` (`Produits_idProduits` ASC),
  INDEX `fk_Membres_has_Produits_Membres1_idx` (`Membres_idMembres` ASC, `Membres_Produits_idProduits` ASC, `Membres_FAQ (questions)_idFAQ (questions)` ASC, `Membres_FAQ (Réponse)_idFAQ (Réponse)` ASC, `Membres_Article_idArticle` ASC),
  CONSTRAINT `fk_Membres_has_Produits_Membres1`
    FOREIGN KEY (`Membres_idMembres`)
    REFERENCES `mydb`.`Membres` (`Me_idMembres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membres_has_Produits_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`Pr_idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Annonce_has_Membres_has_Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Annonce_has_Membres_has_Produits` (
  `Annonce_idAnnonce` INT NOT NULL,
  `Membres_has_Produits_Membres_idMembres` INT NOT NULL,
  `Membres_has_Produits_Membres_Produits_idProduits` INT NOT NULL,
  `Membres_has_Produits_Membres_FAQ (questions)_idFAQ (questions)` INT NOT NULL,
  `Membres_has_Produits_Membres_FAQ (Réponse)_idFAQ (Réponse)` INT NOT NULL,
  `Membres_has_Produits_Membres_Article_idArticle` INT NOT NULL,
  `Membres_has_Produits_Produits_idProduits` INT NOT NULL,
  PRIMARY KEY (`Annonce_idAnnonce`, `Membres_has_Produits_Membres_idMembres`, `Membres_has_Produits_Membres_Produits_idProduits`, `Membres_has_Produits_Membres_FAQ (questions)_idFAQ (questions)`, `Membres_has_Produits_Membres_FAQ (Réponse)_idFAQ (Réponse)`, `Membres_has_Produits_Membres_Article_idArticle`, `Membres_has_Produits_Produits_idProduits`),
  INDEX `fk_Annonce_has_Membres_has_Produits_Membres_has_Produits1_idx` (`Membres_has_Produits_Membres_idMembres` ASC, `Membres_has_Produits_Membres_Produits_idProduits` ASC, `Membres_has_Produits_Membres_FAQ (questions)_idFAQ (questions)` ASC, `Membres_has_Produits_Membres_FAQ (Réponse)_idFAQ (Réponse)` ASC, `Membres_has_Produits_Membres_Article_idArticle` ASC, `Membres_has_Produits_Produits_idProduits` ASC),
  INDEX `fk_Annonce_has_Membres_has_Produits_Annonce1_idx` (`Annonce_idAnnonce` ASC),
  CONSTRAINT `fk_Annonce_has_Membres_has_Produits_Annonce1`
    FOREIGN KEY (`Annonce_idAnnonce`)
    REFERENCES `mydb`.`Annonce` (`An_idAnnonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonce_has_Membres_has_Produits_Membres_has_Produits1`
    FOREIGN KEY (`Membres_has_Produits_Membres_idMembres` , `Membres_has_Produits_Membres_Produits_idProduits` , `Membres_has_Produits_Membres_FAQ (questions)_idFAQ (questions)` , `Membres_has_Produits_Membres_FAQ (Réponse)_idFAQ (Réponse)` , `Membres_has_Produits_Membres_Article_idArticle` , `Membres_has_Produits_Produits_idProduits`)
    REFERENCES `mydb`.`Membres_has_Produits` (`Membres_idMembres` , `Membres_Produits_idProduits` , `Membres_FAQ (questions)_idFAQ (questions)` , `Membres_FAQ (Réponse)_idFAQ (Réponse)` , `Membres_Article_idArticle` , `Produits_idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
